
name: Aula 2 - CI/CD

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java-setup
        with:
          java-version: '17'
          gradle-version: '8.5'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'

      - run: gradle check --info

      - name: Upload Lint Reports
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: build/reports/lint-results.html

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java-setup
        with:
          java-version: '17'
          gradle-version: '8.5'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'

      - run: gradle test --info

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test/

  owasp:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java-setup
        with:
          java-version: '17'
          gradle-version: '8.5'

      - run: gradle dependencyCheckAnalyze

      - name: Upload OWASP Reports
        uses: actions/upload-artifact@v4
        with:
          name: owasp-reports
          path: build/reports/dependency-check-report.html

  build:
      runs-on: ubuntu-latest
      needs: test
  
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/java-setup
          with:
            java-version: '17'
            gradle-version: '8.5'
  
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3
          with:
            gradle-version: '8.5'
  
        - run: gradle bootJar --info
  
        - name: Upload do artefacto
          uses: actions/upload-artifact@v4
          with:
            name: build-output
            path: build/libs/*.jar